version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(asctime)s %(levelname)-8s %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stderr
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
      - stdout
      - stderr
    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
      - queue_handler
